/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EnigmaScoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeDecryption"
      | "confidentialProtocolId"
      | "getCreditScore"
      | "getScoreHistoryCount"
      | "getScoreHistoryEntry"
      | "getUserData"
      | "hasUserData"
      | "queryCreditScore"
      | "requestDecryptionAuthorization"
      | "submitData"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DataSubmitted"
      | "DecryptionAuthorized"
      | "DecryptionRequested"
      | "ScoreCalculated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeDecryption",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreditScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScoreHistoryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScoreHistoryEntry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queryCreditScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryptionAuthorization",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitData",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreditScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScoreHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScoreHistoryEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queryCreditScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryptionAuthorization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitData", data: BytesLike): Result;
}

export namespace DataSubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionAuthorizedEvent {
  export type InputTuple = [
    user: AddressLike,
    authorizedAddress: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    authorizedAddress: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    authorizedAddress: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [
    user: AddressLike,
    requester: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    requester: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    requester: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreCalculatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EnigmaScore extends BaseContract {
  connect(runner?: ContractRunner | null): EnigmaScore;
  waitForDeployment(): Promise<this>;

  interface: EnigmaScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeDecryption: TypedContractMethod<
    [authorizedAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getCreditScore: TypedContractMethod<[user: AddressLike], [string], "view">;

  getScoreHistoryCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getScoreHistoryEntry: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [[string, bigint] & { score: string; timestamp: bigint }],
    "view"
  >;

  getUserData: TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string, string, string] & {
        paymentHistory: string;
        creditUtilization: string;
        accountAge: string;
        transactionFrequency: string;
        debtToIncomeRatio: string;
      }
    ],
    "view"
  >;

  hasUserData: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  queryCreditScore: TypedContractMethod<[user: AddressLike], [string], "view">;

  requestDecryptionAuthorization: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  submitData: TypedContractMethod<
    [
      encryptedPaymentHistory: BytesLike,
      encryptedCreditUtil: BytesLike,
      encryptedAccountAge: BytesLike,
      encryptedTransFreq: BytesLike,
      encryptedDebtIncome: BytesLike,
      proofs: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeDecryption"
  ): TypedContractMethod<
    [authorizedAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCreditScore"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getScoreHistoryCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScoreHistoryEntry"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [[string, bigint] & { score: string; timestamp: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserData"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, string, string, string, string] & {
        paymentHistory: string;
        creditUtilization: string;
        accountAge: string;
        transactionFrequency: string;
        debtToIncomeRatio: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserData"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "queryCreditScore"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "requestDecryptionAuthorization"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitData"
  ): TypedContractMethod<
    [
      encryptedPaymentHistory: BytesLike,
      encryptedCreditUtil: BytesLike,
      encryptedAccountAge: BytesLike,
      encryptedTransFreq: BytesLike,
      encryptedDebtIncome: BytesLike,
      proofs: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DataSubmitted"
  ): TypedContractEvent<
    DataSubmittedEvent.InputTuple,
    DataSubmittedEvent.OutputTuple,
    DataSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionAuthorized"
  ): TypedContractEvent<
    DecryptionAuthorizedEvent.InputTuple,
    DecryptionAuthorizedEvent.OutputTuple,
    DecryptionAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreCalculated"
  ): TypedContractEvent<
    ScoreCalculatedEvent.InputTuple,
    ScoreCalculatedEvent.OutputTuple,
    ScoreCalculatedEvent.OutputObject
  >;

  filters: {
    "DataSubmitted(address,uint256)": TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;
    DataSubmitted: TypedContractEvent<
      DataSubmittedEvent.InputTuple,
      DataSubmittedEvent.OutputTuple,
      DataSubmittedEvent.OutputObject
    >;

    "DecryptionAuthorized(address,address,uint256)": TypedContractEvent<
      DecryptionAuthorizedEvent.InputTuple,
      DecryptionAuthorizedEvent.OutputTuple,
      DecryptionAuthorizedEvent.OutputObject
    >;
    DecryptionAuthorized: TypedContractEvent<
      DecryptionAuthorizedEvent.InputTuple,
      DecryptionAuthorizedEvent.OutputTuple,
      DecryptionAuthorizedEvent.OutputObject
    >;

    "DecryptionRequested(address,address,uint256)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "ScoreCalculated(address,uint256)": TypedContractEvent<
      ScoreCalculatedEvent.InputTuple,
      ScoreCalculatedEvent.OutputTuple,
      ScoreCalculatedEvent.OutputObject
    >;
    ScoreCalculated: TypedContractEvent<
      ScoreCalculatedEvent.InputTuple,
      ScoreCalculatedEvent.OutputTuple,
      ScoreCalculatedEvent.OutputObject
    >;
  };
}
